FROM node:16.18-alpine

WORKDIR /usr/src/app

# Pass secrets as build-time arguments
ARG NODE_ENV
ARG DB_USERNAME
ARG DB_PASSWORD
ARG DB_DATABASE
ARG DB_HOST
ARG DB_DIALECT
ARG DB_USERNAME_PROD
ARG DB_PASSWORD_PROD
ARG DB_DATABASE_PROD
ARG DB_HOST_PROD
ARG DB_DIALECT_PROD

ENV NODE_ENV=$NODE_ENV
ENV DB_USERNAME=$DB_USERNAME
ENV DB_PASSWORD=$DB_PASSWORD
ENV DB_DATABASE=$DB_DATABASE
ENV DB_HOST=$DB_HOST
ENV DB_DIALECT=$DB_DIALECT
ENV DB_USERNAME_PROD=$DB_USERNAME_PROD
ENV DB_PASSWORD_PROD=$DB_PASSWORD_PROD
ENV DB_DATABASE_PROD=$DB_DATABASE_PROD
ENV DB_HOST_PROD=$DB_HOST_PROD
ENV DB_DIALECT_PROD=$DB_DIALECT_PROD

COPY package*.json ./

RUN npm install

COPY . .

RUN export NODE_ENV=development

EXPOSE 3000

CMD [ "node", "server.js" ]

