

  name: Deploy to Cloud Run

  on:
    push:
        branches:
            - api-dev

  jobs:
    deploy:
        runs-on: ubuntu-latest

        steps: 
          - name: Checkout code 
            uses: actions/checkout@v2
        
          - name: Set Up Cloud SDK
            uses: 'google-github-actions/setup-gcloud@v1'
            with:
                version: '>= 416.0.0' 
                project_id: capstone-c23-ps127
                service_account_key: ${{secrets.GCLOUD_AUTH}}

          - name: Configure Docker to use gcloud 
            run: |
                gcloud auth configure-docker asia-southeast2-docker.pkg.dev --quiet
            
          - name: Build and Push Docker Image 
            run: |
                export IMAGE_TAG=$(git rev-parse --short ${{github.sha}})
                export IMAGE_NAME=asia-southeast2-docker.pkg.dev/capstone-c23-ps127/agroconnect/agroconnect-api:${IMAGE_TAG}
                docker build -t ${IMAGE_NAME} .
                docker push ${IMAGE_NAME}

          - name: Deploy to Cloud Run
            run: |
                export IMAGE_TAG=$(git rev-parse --short ${{github.sha}})
                export IMAGE_NAME=asia-southeast2-docker.pkg.dev/capstone-c23-ps127/agroconnect/agroconnect-api:${IMAGE_TAG}
                gcloud run deploy agroconnect-api --image ${IMAGE_NAME} --region asia-southeast2 --allow-unauthenticated
            # env:
            #     CLOUDSDK_METRICS_ENVIRONMENT: github-actions-setup-gcloud
